language: go

go:
  - 1.3

before_install:
  - sudo pip install codecov

install:
  - go get github.com/mattn/gom

script:
  - gom -test install
  - gom test -v -coverprofile=coverage.txt -covermode=count

after_success:
  - codecov
